//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class cp {
    
    private cphoja2[] cphoja2Field;
    
    private int cptoField;
    
    private int tdocField;
    
    private string ndocField;
    
    private string apl1Field;
    
    private string apl2Field;
    
    private string nom1Field;
    
    private string nom2Field;
    
    private string razsocField;
    
    private string nforantField;
    
    private System.DateTime fecfantField;
    
    private bool fecfantFieldSpecified;
    
    private int cantfacField;
    
    private decimal vtconsField;
    
    private decimal vtexenField;
    
    private System.DateTime flimexpField;
    
    private int nitemsField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("cphoja2")]
    public cphoja2[] cphoja2 {
        get {
            return this.cphoja2Field;
        }
        set {
            this.cphoja2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cpto {
        get {
            return this.cptoField;
        }
        set {
            this.cptoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int tdoc {
        get {
            return this.tdocField;
        }
        set {
            this.tdocField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ndoc {
        get {
            return this.ndocField;
        }
        set {
            this.ndocField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string apl1 {
        get {
            return this.apl1Field;
        }
        set {
            this.apl1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string apl2 {
        get {
            return this.apl2Field;
        }
        set {
            this.apl2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nom1 {
        get {
            return this.nom1Field;
        }
        set {
            this.nom1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nom2 {
        get {
            return this.nom2Field;
        }
        set {
            this.nom2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string razsoc {
        get {
            return this.razsocField;
        }
        set {
            this.razsocField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nforant {
        get {
            return this.nforantField;
        }
        set {
            this.nforantField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime fecfant {
        get {
            return this.fecfantField;
        }
        set {
            this.fecfantField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fecfantSpecified {
        get {
            return this.fecfantFieldSpecified;
        }
        set {
            this.fecfantFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cantfac {
        get {
            return this.cantfacField;
        }
        set {
            this.cantfacField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vtcons {
        get {
            return this.vtconsField;
        }
        set {
            this.vtconsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vtexen {
        get {
            return this.vtexenField;
        }
        set {
            this.vtexenField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime flimexp {
        get {
            return this.flimexpField;
        }
        set {
            this.flimexpField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nitems {
        get {
            return this.nitemsField;
        }
        set {
            this.nitemsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class cphoja2 {
    
    private string nfactField;
    
    private System.DateTime ffacField;
    
    private bool ffacFieldSpecified;
    
    private string resfacField;
    
    private System.DateTime fresField;
    
    private bool fresFieldSpecified;
    
    private int tipoField;
    
    private string subpField;
    
    private string descField;
    
    private decimal cunfiField;
    
    private string unfiField;
    
    private decimal cuncoField;
    
    private string uncoField;
    
    private decimal vuniField;
    
    private decimal vtotalField;
    
    private decimal tivaField;
    
    private decimal vexenField;
    
    private int codinsField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nfact {
        get {
            return this.nfactField;
        }
        set {
            this.nfactField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime ffac {
        get {
            return this.ffacField;
        }
        set {
            this.ffacField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ffacSpecified {
        get {
            return this.ffacFieldSpecified;
        }
        set {
            this.ffacFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resfac {
        get {
            return this.resfacField;
        }
        set {
            this.resfacField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime fres {
        get {
            return this.fresField;
        }
        set {
            this.fresField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fresSpecified {
        get {
            return this.fresFieldSpecified;
        }
        set {
            this.fresFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subp {
        get {
            return this.subpField;
        }
        set {
            this.subpField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cunfi {
        get {
            return this.cunfiField;
        }
        set {
            this.cunfiField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unfi {
        get {
            return this.unfiField;
        }
        set {
            this.unfiField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cunco {
        get {
            return this.cuncoField;
        }
        set {
            this.cuncoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unco {
        get {
            return this.uncoField;
        }
        set {
            this.uncoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vuni {
        get {
            return this.vuniField;
        }
        set {
            this.vuniField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vtotal {
        get {
            return this.vtotalField;
        }
        set {
            this.vtotalField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal tiva {
        get {
            return this.tivaField;
        }
        set {
            this.tivaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vexen {
        get {
            return this.vexenField;
        }
        set {
            this.vexenField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int codins {
        get {
            return this.codinsField;
        }
        set {
            this.codinsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CabType {
    
    private string anoField;
    
    private int codCptField;
    
    private string formatoField;
    
    private string versionField;
    
    private string numEnvioField;
    
    private System.DateTime fecEnvioField;
    
    private System.DateTime fecInicialField;
    
    private System.DateTime fecFinalField;
    
    private double valorTotalField;
    
    private string cantRegField;
    
    public CabType() {
        this.formatoField = "640";
        this.versionField = "1";
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string Ano {
        get {
            return this.anoField;
        }
        set {
            this.anoField = value;
        }
    }
    
    /// <comentarios/>
    public int CodCpt {
        get {
            return this.codCptField;
        }
        set {
            this.codCptField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Formato {
        get {
            return this.formatoField;
        }
        set {
            this.formatoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumEnvio {
        get {
            return this.numEnvioField;
        }
        set {
            this.numEnvioField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime FecEnvio {
        get {
            return this.fecEnvioField;
        }
        set {
            this.fecEnvioField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FecInicial {
        get {
            return this.fecInicialField;
        }
        set {
            this.fecInicialField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FecFinal {
        get {
            return this.fecFinalField;
        }
        set {
            this.fecFinalField = value;
        }
    }
    
    /// <comentarios/>
    public double ValorTotal {
        get {
            return this.valorTotalField;
        }
        set {
            this.valorTotalField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CantReg {
        get {
            return this.cantRegField;
        }
        set {
            this.cantRegField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class mas {
    
    private CabType cabField;
    
    private cp[] cpField;
    
    /// <comentarios/>
    public CabType Cab {
        get {
            return this.cabField;
        }
        set {
            this.cabField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("cp")]
    public cp[] cp {
        get {
            return this.cpField;
        }
        set {
            this.cpField = value;
        }
    }
}
