//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcLogOperaciones
    {
        public int intIdLogOprciones { get; set; }
        public Nullable<System.DateTime> fecFcha { get; set; }
        public string varPrcso { get; set; }
        public string varAccion { get; set; }
        public string xmlDatos { get; set; }
        public string varTpo { get; set; }
        public string varUsuario { get; set; }
    }
}
