//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcMenu()
        {
            this.tcRolMenu = new HashSet<tcRolMenu>();
        }
    
        public int intIdMnu { get; set; }
        public string varNmbreOpcion { get; set; }
        public string varCntrller { get; set; }
        public string varAccion { get; set; }
        public string varImgeClass { get; set; }
        public bool bitIsPrent { get; set; }
        public int intPrentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcRolMenu> tcRolMenu { get; set; }
    }
}
