//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcRolMenu
    {
        public int intIdRolMenu { get; set; }
        public Nullable<int> intIdRol { get; set; }
        public Nullable<int> intIdMnu { get; set; }
    
        public virtual tcMenu tcMenu { get; set; }
        public virtual tcRol tcRol { get; set; }
    }
}
