//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcRolUsuario
    {
        public int intIdRolUsuario { get; set; }
        public int intIdUsuario { get; set; }
        public int intIdRol { get; set; }
    
        public virtual tcRol tcRol { get; set; }
        public virtual tcUsuarios tcUsuarios { get; set; }
    }
}
