//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcUsuarios()
        {
            this.tcRolUsuario = new HashSet<tcRolUsuario>();
        }
    
        public int intIdUsuario { get; set; }
        public string varNmbreUsuario { get; set; }
        public string varCdla { get; set; }
        public string varCrgo { get; set; }
        public string varEmail { get; set; }
        public string varLgin { get; set; }
        public string varPssword { get; set; }
        public Nullable<System.DateTime> fecVncmientoPssword { get; set; }
        public Nullable<int> intIntntosPssword { get; set; }
        public Nullable<bool> bitUsuarioBlqueado { get; set; }
        public Nullable<int> intMxmoIntntosPssword { get; set; }
        public Nullable<bool> bitBlqueaUsuario { get; set; }
        public Nullable<bool> bitPsswordCdca { get; set; }
        public Nullable<System.DateTime> fecActlizcionPssword { get; set; }
        public Nullable<int> IntAntguedadPssword { get; set; }
        public string varTlfno { get; set; }
        public Nullable<int> intVncmientoPssword { get; set; }
        public Nullable<int> intFrcuenciaCmbioPssword { get; set; }
        public string varDrccion { get; set; }
        public string varImgFrma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcRolUsuario> tcRolUsuario { get; set; }
    }
}
