//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoDocumentosArchivosAdjuntos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipoDocumentosArchivosAdjuntos()
        {
            this.tmDocumentosAdjuntos = new HashSet<tmDocumentosAdjuntos>();
        }
    
        public int intIdTpoDcmntoArchvosAdjntos { get; set; }
        public string varCdTpoDcmnto { get; set; }
        public string varDscrpcionDcmntos { get; set; }
        public string varFrmlrio { get; set; }
        public string varRuta { get; set; }
        public Nullable<int> intIdRles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmDocumentosAdjuntos> tmDocumentosAdjuntos { get; set; }
    }
}
