//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmAdquiridasComprasTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmAdquiridasComprasTipo()
        {
            this.tmCompras = new HashSet<tmCompras>();
        }
    
        public int intIdAdquirdaTpoCmpra { get; set; }
        public string varCdAdquirdaTpoCmpra { get; set; }
        public string varDscrpcionAdquirdaTpoCmpra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras { get; set; }
    }
}
