//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmCiudades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmCiudades()
        {
            this.tmImportadorExportador = new HashSet<tmImportadorExportador>();
            this.tmProveedores = new HashSet<tmProveedores>();
            this.tmCompras = new HashSet<tmCompras>();
            this.tmTituloMineroProveedor = new HashSet<tmTituloMineroProveedor>();
            this.tmTerceros = new HashSet<tmTerceros>();
            this.tmCompradores = new HashSet<tmCompradores>();
        }

        public int intIdCiudad { get; set; }
        [Display(Name = "Código")]
        public string varCdCiudad { get; set; }
        [Display(Name = "Descripción")]
        public string varDscrpcionCiudad { get; set; }
        [Display(Name = "Abreviatura")]
        public string varAbrvtra { get; set; }
        [Display(Name = "Departamento")]
        public Nullable<int> intIdDprtmnto { get; set; }
        [Display(Name = "Otro Código")]
        public string varCd { get; set; }
        public string varDscrpcionDprtmnto { get; set; }
        public string varNmbreCiudadcrcna { get; set; }
    
        public virtual tmDepartamentos tmDepartamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmImportadorExportador> tmImportadorExportador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmProveedores> tmProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmTituloMineroProveedor> tmTituloMineroProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmTerceros> tmTerceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompradores> tmCompradores { get; set; }
    }
}
