//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tmComprasDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmComprasDetalle()
        {
            this.tmNotasCreditoDetalle = new HashSet<tmNotasCreditoDetalle>();
        }

        public int intIdCmpraDtlle { get; set; }
        public Nullable<int> intIdCmpra { get; set; }
        [DisplayName("Item")]
        public Nullable<int> intCdItem { get; set; }
        [DisplayName("Insumo")]
        public int intIdInsmo { get; set; }
        [DisplayName("Cantidad Factura")]
        public Nullable<decimal> numCntdadFctra { get; set; }
        [DisplayName("Valor Unitario")]
        public Nullable<decimal> numVlorUntrio { get; set; }
        [DisplayName("Cantidad CP")]
        public Nullable<decimal> numCntdadCP { get; set; }
        [DisplayName("Subtotal")]
        public Nullable<decimal> numSbttal { get; set; }
        [DisplayName("% Iva")]
        public Nullable<decimal> numPrcntjeIva { get; set; }
        [DisplayName("Adquirida Tipo Compra")]
        public Nullable<int> intIdAdqurdasTtlo { get; set; }
        [DisplayName("Comentarios")]
        public string varCmntrios { get; set; }
        public Nullable<int> intIdCPDtlle { get; set; }
        [DisplayName("Finos")]
        public Nullable<decimal> numFnos { get; set; }
        [DisplayName("Ley")]
        public Nullable<decimal> numLey { get; set; }
        [DisplayName("Vr Regalías")]
        public Nullable<decimal> numRglias { get; set; }
        [DisplayName("Regalías")]
        public Nullable<int> intIdRglia { get; set; }
        public Nullable<decimal> numVlorUntrioUS { get; set; }
        [DisplayName("% Minería")]
        public Nullable<decimal> numPorcMnria { get; set; }

        public virtual tmCompras tmCompras { get; set; }
        public virtual tmAdquiridas tmAdquiridas { get; set; }
        public virtual tmCPDetalle tmCPDetalle { get; set; }
        public virtual tmInsumos tmInsumos { get; set; }
        public virtual tmRegalias tmRegalias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmNotasCreditoDetalle> tmNotasCreditoDetalle { get; set; }
    }
}
