//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmCompradores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmCompradores()
        {
            this.tmvDEXEncabezado = new HashSet<tmvDEXEncabezado>();
            this.tmvFacturasExportacionEncabezado = new HashSet<tmvFacturasExportacionEncabezado>();
            this.tmCuadrosInsumoProducto = new HashSet<tmCuadrosInsumoProducto>();
            this.tmvFacturasExportacionEncabezado1 = new HashSet<tmvFacturasExportacionEncabezado>();
            this.tmvFacturasExportacionEncabezado2 = new HashSet<tmvFacturasExportacionEncabezado>();
        }
    
        public int intIdCmprdor { get; set; }
        public string varCdCmprdor { get; set; }
        public string varNmbre { get; set; }
        public Nullable<int> intIdCiudad { get; set; }
        public int intIdPais { get; set; }
        public string varDrccion { get; set; }
        public string varTlfno { get; set; }
        public string varEmail { get; set; }
        public string varCiudad { get; set; }
        public string varFax { get; set; }
        public string varCntcto { get; set; }
        public Nullable<decimal> numDiasCrtra { get; set; }
        public Nullable<decimal> numTipoDocumento { get; set; }
        public Nullable<int> intIdCmpnia { get; set; }
        public string varOtroCdgo { get; set; }
        public string varAbrvtraCmprdor { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public Nullable<int> intIdIncterms { get; set; }
        public Nullable<int> intIdMnda { get; set; }
        public Nullable<int> intIdFrmaPgo { get; set; }
        public Nullable<int> intIdClsfccionPrvdor { get; set; }
        public Nullable<int> intIdVnddor { get; set; }
        public Nullable<int> intIdNvra { get; set; }
        public Nullable<int> intIdPuertoDspcho { get; set; }
        public Nullable<int> intIdPuertoDstno { get; set; }
        public Nullable<int> intIdPlntaDspchdra { get; set; }
        public string varCiudadIncoterm { get; set; }
        public Nullable<int> intIdTrnsprte { get; set; }
        public Nullable<int> intIdTposEmblje { get; set; }
        public Nullable<int> intIdTpoEmblje { get; set; }
        public Nullable<System.DateTime> fecMxma { get; set; }
    
        public virtual tmPaises tmPaises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXEncabezado> tmvDEXEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado { get; set; }
        public virtual tmCiudades tmCiudades { get; set; }
        public virtual tmIncoterms tmIncoterms { get; set; }
        public virtual tmLugaresEmbarque tmLugaresEmbarque { get; set; }
        public virtual tmLugaresEmbarque tmLugaresEmbarque1 { get; set; }
        public virtual tmMonedas tmMonedas { get; set; }
        public virtual tmTerceros tmTerceros { get; set; }
        public virtual tmTransportes tmTransportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCuadrosInsumoProducto> tmCuadrosInsumoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado2 { get; set; }
    }
}
