//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmCuadrosInsumoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmCuadrosInsumoProducto()
        {
            this.tmvDEXDetalle = new HashSet<tmvDEXDetalle>();
            this.tmInsumos = new HashSet<tmInsumos>();
            this.tmPosicionesArancelarias = new HashSet<tmPosicionesArancelarias>();
            this.tmPosicionesArancelarias1 = new HashSet<tmPosicionesArancelarias>();
            this.tmvFacturasExportacionDetalle = new HashSet<tmvFacturasExportacionDetalle>();
            this.tmvFacturasExportacionDetalle1 = new HashSet<tmvFacturasExportacionDetalle>();
            this.tmvProductosFacturacion = new HashSet<tmvProductosFacturacion>();
            this.tmvProductosFacturacion1 = new HashSet<tmvProductosFacturacion>();
        }
    
        public int intIdCuadroInsmoPrdcto { get; set; }
        public string varCdCuadroInsmoPrdcto { get; set; }
        public int intIdPrdcto { get; set; }
        public Nullable<decimal> numVlorFob { get; set; }
        public Nullable<decimal> numPsoNto { get; set; }
        public int intIdUndad { get; set; }
        public Nullable<decimal> numFctorDianMncmex { get; set; }
        public Nullable<int> intIdUndadCrtfcdoOrgen { get; set; }
        public Nullable<int> intIdExprtdor { get; set; }
        public Nullable<int> intIdCuadroCI { get; set; }
        public Nullable<bool> bitBlqueo { get; set; }
        public string varCdgoOrdnrio { get; set; }
        public Nullable<System.DateTime> fecRdccion { get; set; }
        public Nullable<System.DateTime> fecAprbcion { get; set; }
        public Nullable<System.DateTime> fecVncmientoCrtfcdoOrgen { get; set; }
        public int intIdPlanIncial { get; set; }
        public Nullable<int> intIdImprtdor { get; set; }
        public Nullable<int> intIdCmprdor { get; set; }
        public Nullable<decimal> numVlorAgrgdoNcional { get; set; }
        public Nullable<decimal> numPrcntjeAgrgdoNcional { get; set; }
        public Nullable<decimal> numVlorAgrgdoExtrno { get; set; }
        public Nullable<decimal> numPrcntjeAgrgdoExtrno { get; set; }
        public Nullable<decimal> numPrcioMxmo { get; set; }
        public Nullable<decimal> numPrcioMnmo { get; set; }
        public string varCmntrio { get; set; }
        public string varCmntrioRsduo { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public Nullable<int> intIdCmpnia { get; set; }
        public Nullable<int> intIdIntrfceErrorAudtoriaDtos { get; set; }
        public Nullable<bool> bitDfcto { get; set; }
        public Nullable<int> intIdRfrncia { get; set; }
    
        public virtual tmImportadorExportador tmImportadorExportador { get; set; }
        public virtual tmUnidades tmUnidades { get; set; }
        public virtual tmUnidades tmUnidades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXDetalle> tmvDEXDetalle { get; set; }
        public virtual tmCompradores tmCompradores { get; set; }
        public virtual tmImportadorExportador tmImportadorExportador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmInsumos> tmInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmPosicionesArancelarias> tmPosicionesArancelarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmPosicionesArancelarias> tmPosicionesArancelarias1 { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto1 { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionDetalle> tmvFacturasExportacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionDetalle> tmvFacturasExportacionDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion1 { get; set; }
    }
}
