//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmDepartamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmDepartamentos()
        {
            this.tmCiudades = new HashSet<tmCiudades>();
            this.tmImportadorExportador = new HashSet<tmImportadorExportador>();
        }

        public int intIdDprtmnto { get; set; }
        [Display(Name = "Código")]
        public string varCdDprtmnto { get; set; }
        [Display(Name = "Descripción")]
        public string varDscrpcionDprtmnto { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCiudades> tmCiudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmImportadorExportador> tmImportadorExportador { get; set; }
    }
}
