//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmImportadorExportador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmImportadorExportador()
        {
            this.tmPlanesCI = new HashSet<tmPlanesCI>();
            this.tmvDEXEncabezado = new HashSet<tmvDEXEncabezado>();
            this.tmCuadrosInsumoProducto = new HashSet<tmCuadrosInsumoProducto>();
            this.tmvFacturasExportacionEncabezado = new HashSet<tmvFacturasExportacionEncabezado>();
            this.tmCompras = new HashSet<tmCompras>();
            this.tmCompras1 = new HashSet<tmCompras>();
            this.tmCuadrosInsumoProducto1 = new HashSet<tmCuadrosInsumoProducto>();
            this.tmResolucionesImportadorExportador = new HashSet<tmResolucionesImportadorExportador>();
            this.tmvProductosFacturacion = new HashSet<tmvProductosFacturacion>();
        }
    
        public int intIdImprtdorExprtdor { get; set; }
        public string varNitImprtdorExprtdor { get; set; }
        public string varNmbre { get; set; }
        public Nullable<int> intIdPais { get; set; }
        public string varDrccion { get; set; }
        public string varTlfno { get; set; }
        public string varFax { get; set; }
        public string varEmail { get; set; }
        public string varCntcto { get; set; }
        public Nullable<int> intIdCiudad { get; set; }
        public string varNmbreRvsorFscal { get; set; }
        public string varNmbreRprsntnteLgal { get; set; }
        public string varDgtoVrfccion { get; set; }
        public string varRzonSocial { get; set; }
        public string varAltex { get; set; }
        public string varRgstroCI { get; set; }
        public Nullable<System.DateTime> fecRgstroCI { get; set; }
        public string varCdUsuarioAduanro { get; set; }
        public string varActEcnmca { get; set; }
        public Nullable<int> intIdNvelCmrcial { get; set; }
        public Nullable<int> intIdTpoImprtdorExprtdor { get; set; }
        public Nullable<int> intIdDprtmnto { get; set; }
        public string varCdImprtdorExprtdor { get; set; }
        public Nullable<int> intIdAduana { get; set; }
        public Nullable<int> intIdCmpnia { get; set; }
        public Nullable<int> intIdTpoDcmntoIdntfccion { get; set; }
        public string varAplldos1 { get; set; }
        public string varAplldos2 { get; set; }
        public string varNmbre1 { get; set; }
        public string varNmbre2 { get; set; }
        public Nullable<int> intIdVnddor { get; set; }
        public string varCiudad { get; set; }
        public Nullable<int> intIdTrcro { get; set; }
        public string varEmailScndrio { get; set; }
        public string varNmbreCmrcial { get; set; }
        public string varLgo { get; set; }
        public Nullable<bool> bitFltroOrdenCmpra { get; set; }
        public string varFairminedId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmPlanesCI> tmPlanesCI { get; set; }
        public virtual tmCiudades tmCiudades { get; set; }
        public virtual tmPaises tmPaises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXEncabezado> tmvDEXEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCuadrosInsumoProducto> tmCuadrosInsumoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras1 { get; set; }
        public virtual tmAduanas tmAduanas { get; set; }
        public virtual tmDepartamentos tmDepartamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCuadrosInsumoProducto> tmCuadrosInsumoProducto1 { get; set; }
        public virtual tmTerceros tmTerceros { get; set; }
        public virtual tmTerceros tmTerceros1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmResolucionesImportadorExportador> tmResolucionesImportadorExportador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion { get; set; }
    }
}
