//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmInsumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmInsumos()
        {
            this.tmComprasDetalle = new HashSet<tmComprasDetalle>();
            this.tmvProductosFacturacion = new HashSet<tmvProductosFacturacion>();
        }

        public int intIdInsmo { get; set; }
        [Display(Name = "Código")]
        public string varCdInsmo { get; set; }
        [Display(Name = "Pos. Arancelaria")]
        public int intIdPscionArnclria { get; set; }
        [Display(Name = "Unidad")]
        public int intIdUndad { get; set; }
        [Display(Name = "Unidad Dian")]
        public int intIdUndadDian { get; set; }
        [Display(Name = "Descripción")]
        public string varDscrpcionInsmo { get; set; }
        [Display(Name = "Tipo Material")]
        public Nullable<int> intIdLnea { get; set; }
        [Display(Name = "Unidad Compra")]
        public Nullable<int> intIdUndadCmpra { get; set; }
        [Display(Name = "Insumo Nacional")]
        public Nullable<bool> bitInsmoNcional { get; set; }
        [Display(Name = "Estado Mercancía")]
        public Nullable<int> intIdTpoCmpra { get; set; }
        [Display(Name = "Factor")]
        public Nullable<decimal> numFctorMncmex { get; set; }
        public string varTpo { get; set; }
        public string varMrcaCmrcial { get; set; }
        public string varCdInvntrio { get; set; }
        public string varCdCliente { get; set; }
        public string varCdPdreInsmo { get; set; }
        public string varDscrpcionInsmoIngles { get; set; }
        public string varDscrpcionInsmoRgstro { get; set; }
        public Nullable<int> intIdNtrlza { get; set; }
        public Nullable<int> intIdRfrncia { get; set; }
        public Nullable<decimal> numPsoLqudcionEmbrque { get; set; }
        public Nullable<decimal> numFctorCnvrsionEmbrque { get; set; }
        public Nullable<bool> bitBlqueo { get; set; }
        public Nullable<int> intIdTpoPrdcto { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public string varClse { get; set; }
        public string varClsfccion { get; set; }
        public string varDscrpcionOrden { get; set; }
        public string varClor { get; set; }
        public string varRfrncia { get; set; }
        public Nullable<decimal> numFctorSlctudCmpra { get; set; }
        public string varNmbreCmrcial { get; set; }
        public string varMdlo { get; set; }
        public string varDscrpcionCrctrstcas { get; set; }
        public Nullable<int> intIdCmpnia { get; set; }
        public Nullable<decimal> numVlmen { get; set; }
        public Nullable<decimal> numOtroFctor { get; set; }
        public Nullable<decimal> numPsoNto { get; set; }
        public Nullable<decimal> numPsoBrto { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public Nullable<int> intIdPrdctoFctrcionMqula { get; set; }
        public Nullable<decimal> numFctorMqula { get; set; }
        public string varAnoFbrccion { get; set; }
        public Nullable<int> intIdEstdoLquidcionEmbrque { get; set; }
        public string varTpoAndnaVlor { get; set; }
        public Nullable<bool> bitExpcionRegstro { get; set; }
        public Nullable<System.DateTime> fecCreacion { get; set; }
        public Nullable<int> intIdGnero { get; set; }
        public Nullable<decimal> numPrctjeDscprdcio { get; set; }
        public Nullable<int> intIdCuadroIntgrcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmComprasDetalle> tmComprasDetalle { get; set; }
        public virtual tmComprasTipo tmComprasTipo { get; set; }
        public virtual tmLineas tmLineas { get; set; }
        public virtual tmPosicionesArancelarias tmPosicionesArancelarias { get; set; }
        public virtual tmUnidades tmUnidades { get; set; }
        public virtual tmUnidades tmUnidades1 { get; set; }
        public virtual tmUnidades tmUnidades2 { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion { get; set; }
    }
}
