//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmLugaresEmbarque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmLugaresEmbarque()
        {
            this.tmvDEXEncabezado = new HashSet<tmvDEXEncabezado>();
            this.tmCompras = new HashSet<tmCompras>();
            this.tmCompradores = new HashSet<tmCompradores>();
            this.tmCompradores1 = new HashSet<tmCompradores>();
            this.tmProveedores = new HashSet<tmProveedores>();
            this.tmvFacturasExportacionEncabezado = new HashSet<tmvFacturasExportacionEncabezado>();
            this.tmvFacturasExportacionEncabezado1 = new HashSet<tmvFacturasExportacionEncabezado>();
        }
    
        public int intIdLgarEmbrque { get; set; }
        public string varCdLgarEmbrque { get; set; }
        public string varNmbreLgarEmbrque { get; set; }
        public Nullable<int> intIdPais { get; set; }
    
        public virtual tmPaises tmPaises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXEncabezado> tmvDEXEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompradores> tmCompradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompradores> tmCompradores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmProveedores> tmProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado1 { get; set; }
    }
}
