//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmNotasCreditoEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmNotasCreditoEncabezado()
        {
            this.tmNotasCreditoDetalle = new HashSet<tmNotasCreditoDetalle>();
        }
    
        public int intIdNtaCrdto { get; set; }
        public string varNtaCrdto { get; set; }
        public Nullable<System.DateTime> fecNtaCrdto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmNotasCreditoDetalle> tmNotasCreditoDetalle { get; set; }
    }
}
