//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmNotificaciones
    {
        public int intIdNtfccion { get; set; }
        public string varUrl { get; set; }
        public string varIcno { get; set; }
        public string varNmbre { get; set; }
        public string varDscrpcion { get; set; }
        public string intCntdad { get; set; }
    }
}
