//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmNotasCreditoDetalle
    {
        public int intIdNtaCrdtoDtlle { get; set; }
        public int intIdNtaCrdto { get; set; }
        public int intIdCmpraDtlle { get; set; }
        public Nullable<decimal> numCntdad { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public Nullable<decimal> numSbttal { get; set; }
    
        public virtual tmComprasDetalle tmComprasDetalle { get; set; }
        public virtual tmNotasCreditoEncabezado tmNotasCreditoEncabezado { get; set; }
    }
}
