//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmPaises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmPaises()
        {
            this.tmImportadorExportador = new HashSet<tmImportadorExportador>();
            this.tmProveedores = new HashSet<tmProveedores>();
            this.tmCompradores = new HashSet<tmCompradores>();
            this.tmLugaresEmbarque = new HashSet<tmLugaresEmbarque>();
            this.tmTerceros = new HashSet<tmTerceros>();
        }
    
        public int intIdpais { get; set; }
        public string varCdPais { get; set; }
        public string varDscrpcionPais { get; set; }
        public string varAbrvtra { get; set; }
        public Nullable<int> intIdZnaGeogrfca { get; set; }
        public string varDscrpcionPaisIngles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmImportadorExportador> tmImportadorExportador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmProveedores> tmProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompradores> tmCompradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmLugaresEmbarque> tmLugaresEmbarque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmTerceros> tmTerceros { get; set; }
    }
}
