//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmPlanesCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmPlanesCI()
        {
            this.tmCPEncabezado = new HashSet<tmCPEncabezado>();
            this.tmvDEXEncabezado = new HashSet<tmvDEXEncabezado>();
        }

        public int intIdPlanCI { get; set; }
        [Display(Name = "Código")]
        public string varCdPlanCI { get; set; }
        [Display(Name = "Descripción")]
        public string varDscrpcionPlanCI { get; set; }
        [Display(Name = "F. Presentación")]
        public Nullable<System.DateTime> FecPrsntcion { get; set; }
        [Display(Name = "F. Fin Expo.")]
        public Nullable<System.DateTime> FecFnalExprtcion { get; set; }
        [Display(Name = "F. Fin Comp.")]
        public Nullable<System.DateTime> FecFnalCmpras { get; set; }
        [Display(Name = "Exportador")]
        public Nullable<int> intIdImprtdorExprtdor { get; set; }
        [Display(Name = "Bloqueado")]
        public Nullable<bool> bitBloqueo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCPEncabezado> tmCPEncabezado { get; set; }
        public virtual tmImportadorExportador tmImportadorExportador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXEncabezado> tmvDEXEncabezado { get; set; }
    }
}
