//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmPosicionesArancelarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmPosicionesArancelarias()
        {
            this.tmInsumos = new HashSet<tmInsumos>();
            this.tmvProductosFacturacion = new HashSet<tmvProductosFacturacion>();
            this.tmvFacturasExportacionDetalle = new HashSet<tmvFacturasExportacionDetalle>();
        }

        public int intIdPscionArnclria { get; set; }
        [Display(Name = "P. Arancelaria")]
        public string varPscionArnclria { get; set; }
        [Display(Name = "% Arancel")]
        public Nullable<decimal> numPrcntjeArncel { get; set; }
        [Display(Name = "% Iva")]
        public Nullable<decimal> numPrcntjeIva { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Descripción")]
        public string varDscrpcionPscionArnclria { get; set; }
        [Display(Name = "Unidad")]
        public Nullable<int> intIdUndad { get; set; }
        public string varPscionNldsa { get; set; }
        public string varPscionNblalc { get; set; }
        public string varDscrpcionRgstro { get; set; }
        public string varDscrpcionCrtfcdo { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public string varCdPscionArnclria { get; set; }
        public string varCodCmplmntrio { get; set; }
        public string varCodSplmntrio { get; set; }
        public Nullable<int> intIdCuadroInsmoPrdcto { get; set; }
        public Nullable<int> intIdCuadroInsmoPrdctoOrdnrio { get; set; }
        public Nullable<int> intIdLnea { get; set; }
        public Nullable<int> intIdRfrncia { get; set; }
        public Nullable<int> intIdNtrlza { get; set; }
        public Nullable<int> intIdTpoPrdcto { get; set; }
        public Nullable<int> intIdGnero { get; set; }
        public Nullable<decimal> numVlorSbreCrgo { get; set; }
        public Nullable<bool> bitAplca { get; set; }
        public Nullable<int> intIdClsfccionPscionArnclria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmInsumos> tmInsumos { get; set; }
        public virtual tmUnidades tmUnidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto1 { get; set; }
        public virtual tmPosicionesArancelarias tmPosicionesArancelarias1 { get; set; }
        public virtual tmPosicionesArancelarias tmPosicionesArancelarias2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionDetalle> tmvFacturasExportacionDetalle { get; set; }
    }
}
