//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmptmvDEXDetalleInterface
    {
        public string C4_detalleNumeroFormulario { get; set; }
        public string C98_numeroSerie { get; set; }
        public string C99_subPartida { get; set; }
        public string C100_codigoComplementario { get; set; }
        public string C101_codigoSuplementario { get; set; }
        public string C102_unidadFisica { get; set; }
        public string C102a_UnidadFisicaCodigo { get; set; }
        public string C103_cantidadUnidadFisica { get; set; }
        public string C104_unidadComercial { get; set; }
        public string C104a_unidadComercialCodigo { get; set; }
        public string C105_cantidadUnidadComercial { get; set; }
        public string C106_clasesEmbalaje { get; set; }
        public string C106a_clasesEmbalajeCodigo { get; set; }
        public string C107_numeroBultos { get; set; }
        public string C108_pesoBrutoKilogramo { get; set; }
        public string C109_pesoNetoKilogramo { get; set; }
        public string C110_valorFobUsd { get; set; }
        public string C111_marcas { get; set; }
        public string C112_descripcionSubpartida { get; set; }
        public string C113_unidadMedidaPlazo { get; set; }
        public string C114_plazo { get; set; }
        public string C115_paisOrigen { get; set; }
        public string C115a_paisOrigenCodigo { get; set; }
        public string C116_regionPaisOrigen { get; set; }
        public string C116a_regionPaisOrigenCodigo { get; set; }
        public string C117_preferenciaArancelaria { get; set; }
        public string C118_aduanaPrecedente { get; set; }
        public string C118a_aduanaPrecedenteCodigo { get; set; }
        public string C119_numeroDeclaracionPrecedente { get; set; }
        public string C120_anoAceptacion { get; set; }
        public string C121_regimenPrecendente { get; set; }
        public string C121a_regimenPrecendente { get; set; }
        public string C122_codigoModalidadPrecedente { get; set; }
        public string C123_numeroSeriePrecedente { get; set; }
        public string C117a_preferenciaArancelariaCodigo { get; set; }
        public int intIdTmptmvDEXDetalleInterface { get; set; }
    
        public virtual tmpTmvDEXEncabezadoInterface tmpTmvDEXEncabezadoInterface { get; set; }
    }
}
