//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTmvDEXEncabezadoTransportadorInterface
    {
        public string C4_transNumeroFormulario { get; set; }
        public string C124_trasn1TipoDocumento { get; set; }
        public string C125_trans1Nit { get; set; }
        public string C126_trans1DigitoVerificacion { get; set; }
        public string C127_trasn1PrimerApellido { get; set; }
        public string C128_trans1SegundoApellido { get; set; }
        public string C129_trans1PrimerNombre { get; set; }
        public string C130_trasn1OtrosNombres { get; set; }
        public string C131_trans1RazonSocial { get; set; }
        public string C132_trans1NacionalidadBandera { get; set; }
        public string C132a_trans1NacionalidadBanderaCodigo { get; set; }
        public string C133_trans1ManifiestoCarga { get; set; }
        public string C134_trans1FechaManifiesto { get; set; }
        public string C135_trans1IdentificacionMedioTransporte { get; set; }
        public string C136_trans1LugarEmbarque { get; set; }
        public string C136a_trans1LugarEmbarqueCodigo { get; set; }
        public int intIdTmpTmvDEXEncabezadoTransportadorInterface { get; set; }
    
        public virtual tmpTmvDEXEncabezadoInterface tmpTmvDEXEncabezadoInterface { get; set; }
    }
}
