//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTmvCpDetalleInterface
    {
        public string C4_DetalleNumeroFormulario { get; set; }
        public string C40_NoFactura { get; set; }
        public string C41_FecFactura { get; set; }
        public string C42_NoResolFactura { get; set; }
        public string C43_FecFactura { get; set; }
        public string C44_TipoProdServicio { get; set; }
        public string C44a_CodTipoProdServicio { get; set; }
        public string C45_Subpartida { get; set; }
        public string C46_DescripcionMercancia { get; set; }
        public string C47_CantUnidadFisica { get; set; }
        public string C48_UnidadFisica { get; set; }
        public string C48a_CodUnidadFisica { get; set; }
        public string C49_CantUnidadCmrcial { get; set; }
        public string C50_UnidadComercial { get; set; }
        public string C50a_CodUnidadComercial { get; set; }
        public string C51_ValorUnitario { get; set; }
        public string C52_ValorTotal { get; set; }
        public string C53_TarifaIva { get; set; }
        public string C54_ValorExcencionIva { get; set; }
        public string C55_CodInsumo { get; set; }
        public int intId { get; set; }
    
        public virtual tmpTmvCpEncabezadoInterface tmpTmvCpEncabezadoInterface { get; set; }
    }
}
