//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTmvDEXEncabezadoSoporteInterface
    {
        public string C4_soporteNumeroFormulario { get; set; }
        public string C137_soporte1NumeroSerie { get; set; }
        public string C138_soporte1CodigoTipoDocumento { get; set; }
        public string C139_soporte1Descripcion { get; set; }
        public string C140_soporte1NumeroDocumento { get; set; }
        public string C141_soporte1NumeroIdentficacionEmisor { get; set; }
        public string C142_soporte1DigitoVerificacion { get; set; }
        public string C143_soporte1NombreEmisor { get; set; }
        public string C144_soporte1FechaExpedicion { get; set; }
        public string C145_soporte1FechaVencimiento { get; set; }
        public string C146_soporte1CodigoMoneda { get; set; }
        public string C147_soporte1montoDocumento { get; set; }
        public string C148_soporte1UnidadComercial { get; set; }
        public string C148_soporte1UnidadComercialCodigo { get; set; }
        public string C149_soporte1CantidadUnidadComercial { get; set; }
        public int intIdTmpTmvDEXEncabezadoSoporteInterface { get; set; }
    
        public virtual tmpTmvDEXEncabezadoInterface tmpTmvDEXEncabezadoInterface { get; set; }
    }
}
