//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmptmvDEXDetalleCpsInterface
    {
        public string C4_detalleNumeroFormulario { get; set; }
        public string Cp { get; set; }
        public int intIdtmptmvDEXDetalleCpsInterface { get; set; }
    
        public virtual tmpTmvDEXEncabezadoInterface tmpTmvDEXEncabezadoInterface { get; set; }
    }
}
