//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmptmvDEXDetalleContinuacionInterface
    {
        public string C4_detalleContinuacionNumeroFormulario { get; set; }
        public string C172_numeroSerie { get; set; }
        public string C112_descripcionSubpartida { get; set; }
        public int intIdCntnuacionDscrpcionDtlle { get; set; }
    
        public virtual tmpTmvDEXEncabezadoInterface tmpTmvDEXEncabezadoInterface { get; set; }
    }
}
