//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTmvDEXEncabezadoInterface
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmpTmvDEXEncabezadoInterface()
        {
            this.tmptmvDEXDetalleContinuacionInterface = new HashSet<tmptmvDEXDetalleContinuacionInterface>();
            this.tmptmvDEXDetalleInterface = new HashSet<tmptmvDEXDetalleInterface>();
            this.tmpTmvDEXEncabezadoSoporteInterface = new HashSet<tmpTmvDEXEncabezadoSoporteInterface>();
            this.tmpTmvDEXEncabezadoTransportadorInterface = new HashSet<tmpTmvDEXEncabezadoTransportadorInterface>();
            this.tmptmvDEXDetalleCpsInterface = new HashSet<tmptmvDEXDetalleCpsInterface>();
        }
    
        public string C1_ano { get; set; }
        public string C4_numeroFormulario { get; set; }
        public string C6_expoDigitoVerificacion { get; set; }
        public string C7_expoPrimerApellido { get; set; }
        public string C8_expoSegundoApellido { get; set; }
        public string C9_expoPrimer_nombre { get; set; }
        public string C10_expoOtrosNombres { get; set; }
        public string C11_expoRazonSocial { get; set; }
        public string C18_expoNit { get; set; }
        public string C20_expoTipoDocumento { get; set; }
        public string C24_declaTipoDocumento { get; set; }
        public string C25_declaNit { get; set; }
        public string C26_declaDigitoVerificacion { get; set; }
        public string C27_declaPrimerApellido { get; set; }
        public string C28_declaSegundoApellido { get; set; }
        public string C29_declaPrimerNombre { get; set; }
        public string C30_declaOtrosNombres { get; set; }
        public string C31_declaRazonSocial { get; set; }
        public string C32_clienteTipoDocumento { get; set; }
        public string C33_nit { get; set; }
        public string C34_primerApellido { get; set; }
        public string C35_segundoApellido { get; set; }
        public string C36_primerNombre { get; set; }
        public string C37_otrosNombres { get; set; }
        public string C38_clienteRazonSocial { get; set; }
        public string C39_clienteDirreccion { get; set; }
        public string C40_clienteCiudad { get; set; }
        public string C41_claseDex { get; set; }
        public string C41a_claseDexCodigo { get; set; }
        public string C42_formularioAnterior { get; set; }
        public string C43_tipoDiligenciamiento { get; set; }
        public string C43a_tipoDiligenciamientoCodigo { get; set; }
        public string C44_tipoDespacho { get; set; }
        public string C44a_tipoDespachoCodigo { get; set; }
        public string C45_tipoCorrecion { get; set; }
        public string C45a_tipoCorrecionCodigo { get; set; }
        public string C46_numeroReferencia { get; set; }
        public string C47_numeroProgramaEspecialMuestras { get; set; }
        public string C48_numeroAutorizacionEmbarque { get; set; }
        public string C49_regimenAduanero { get; set; }
        public string C49a_regimenAduaneroCodigo { get; set; }
        public string C50_aduanaDespacho { get; set; }
        public string C51a_aduanaDespacho { get; set; }
        public string C51_codigoPaisTramite { get; set; }
        public string C52_codigoRegionProcedencia { get; set; }
        public string C53_tipoDatos { get; set; }
        public string C53a_tiposDatosCodigo { get; set; }
        public string C54_tipoEmbaque { get; set; }
        public string C54_tipoEmbarqueCodigo { get; set; }
        public string C55_codigoNaturalezaTransaccion { get; set; }
        public string C56_codigoIncoterms { get; set; }
        public string C57_lugarEntrega { get; set; }
        public string C58_codigoMonedaTransaccion { get; set; }
        public string C59_valorfacturaMonedaTransaccion { get; set; }
        public string C60_tasaCambio { get; set; }
        public string C61_formaPago { get; set; }
        public string C61_formaPagoCodigo { get; set; }
        public string C62_cantidadPagoAnticipados { get; set; }
        public string C63_fecha1PagoAnticipado { get; set; }
        public string C64_mercaciaManoViajeroSi { get; set; }
        public string C64a_mercanciaManoViajeroNO { get; set; }
        public string C65_sistemasEspecialesSI { get; set; }
        public string C65a_sistemasEspecialesNo { get; set; }
        public string C66_exportacionTransitoSi { get; set; }
        public string C66a_exportacionTransitoNo { get; set; }
        public string C67_modoTransporte { get; set; }
        public string C67a_modoTransporteCodigo { get; set; }
        public string C68_tipoCarga { get; set; }
        public string C68_tipoCargaCodigo { get; set; }
        public string C69_aduanaSalida { get; set; }
        public string C69a_aduanaSalidaCodigo { get; set; }
        public string C70_paisDestinoFinal { get; set; }
        public string C70a_paisDestinoFinalCodigo { get; set; }
        public string C71_codigoDestinoFinal { get; set; }
        public string C72_valorFobUsd { get; set; }
        public string C73_valorFletesUsd { get; set; }
        public string C74_valorSegurosUsd { get; set; }
        public string C75_valorOtrosGastosUsd { get; set; }
        public string C76_valorTotalExportacion { get; set; }
        public string C77_valorReintegroUsd { get; set; }
        public string C78_totalVanUsd { get; set; }
        public string C79_totalSeries { get; set; }
        public string C80_totalBultos { get; set; }
        public string C81_totalPesoBruto { get; set; }
        public string C82_numeroAceptacion { get; set; }
        public string C83_fechaAceptacion { get; set; }
        public string C84_numeroAutorizacionEmbarque { get; set; }
        public string C85_fechaAutorizacionEmbarque { get; set; }
        public string C86_nombreFuncionarioResponsable { get; set; }
        public string C87_cargo { get; set; }
        public string C88_tipoDocumento { get; set; }
        public string C89_numeroDocumentoIdentificacion { get; set; }
        public string C90_numeroRadicacion { get; set; }
        public string C997_fechaAceptacion { get; set; }
        public string C1001_apellidosNombresQuienSuscribeDocumento { get; set; }
        public string C1002_tipoDocumentoQuienSuscribeDocumento { get; set; }
        public string C1003_numeroIdentificacionQuienSuscribeDocumento { get; set; }
        public string C1004_digitoVerificacionQuienSuscribeDocumento { get; set; }
        public string C1005_codigoRepresentacionQuienSuscribeDocumento { get; set; }
        public string C1006_organizacionQuienSuscribeDocumento { get; set; }
        public string nombreArchivo { get; set; }
        public Nullable<int> intIdIntrfceErrores { get; set; }
        public string archivoAdjunto { get; set; }
        public Nullable<int> intIdTpoDex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmptmvDEXDetalleContinuacionInterface> tmptmvDEXDetalleContinuacionInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmptmvDEXDetalleInterface> tmptmvDEXDetalleInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmpTmvDEXEncabezadoSoporteInterface> tmpTmvDEXEncabezadoSoporteInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmpTmvDEXEncabezadoTransportadorInterface> tmpTmvDEXEncabezadoTransportadorInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmptmvDEXDetalleCpsInterface> tmptmvDEXDetalleCpsInterface { get; set; }
    }
}
