//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmRemisionDocumentos
    {
        public int intIdRmsion { get; set; }
        public Nullable<int> intIdPrvdor { get; set; }
        public Nullable<int> intMes { get; set; }
        public Nullable<System.DateTime> fecEnvio { get; set; }
        public string varNumGuiaEnvio { get; set; }
        public Nullable<System.DateTime> fecRcbdo { get; set; }
        public Nullable<System.DateTime> fecEntrgaCliente { get; set; }
        public string varQuienRcbe { get; set; }
        public Nullable<System.DateTime> fecDspcho { get; set; }
        public string varNumGuiaDspacho { get; set; }
    
        public virtual tmProveedores tmProveedores { get; set; }
    }
}
