//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmRegalias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmRegalias()
        {
            this.tmCompras = new HashSet<tmCompras>();
            this.tmComprasDetalle = new HashSet<tmComprasDetalle>();
        }

        public int intIdRglia { get; set; }
        [Display(Name = "F. Inicio")]
        public Nullable<System.DateTime> fecIncioPriodo { get; set; }
        [Display(Name = "F. Fin")]
        public Nullable<System.DateTime> fecFinPriodo { get; set; }
        [Display(Name = "Valor Base")]
        public Nullable<decimal> numVlorPorGrmo { get; set; }
        public Nullable<decimal> numBse { get; set; }
        [Display(Name = "Tipo Material")]
        public Nullable<int> intIdLnea { get; set; }
        [Display(Name = "Año")]
        public Nullable<int> intAno { get; set; }
        [Display(Name = "Mes")]
        public Nullable<int> intMes { get; set; }
        
    
        public virtual tmLineas tmLineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmComprasDetalle> tmComprasDetalle { get; set; }
    }
}
