//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmTerceros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmTerceros()
        {
            this.tmvDEXEncabezado = new HashSet<tmvDEXEncabezado>();
            this.tmvDEXEncabezado1 = new HashSet<tmvDEXEncabezado>();
            this.tmCompradores = new HashSet<tmCompradores>();
            this.tmImportadorExportador = new HashSet<tmImportadorExportador>();
            this.tmImportadorExportador1 = new HashSet<tmImportadorExportador>();
            this.tmvFacturasExportacionEncabezado = new HashSet<tmvFacturasExportacionEncabezado>();
            this.tmvFacturasExportacionEncabezado1 = new HashSet<tmvFacturasExportacionEncabezado>();
        }
    
        public int intIdTrcro { get; set; }
        public string varCdTrcro { get; set; }
        public string varNmbre { get; set; }
        public string varTlfno { get; set; }
        public Nullable<int> intIdPais { get; set; }
        public string varDrccion { get; set; }
        public string varCntcto { get; set; }
        public string varEmail { get; set; }
        public Nullable<int> intIdCiudad { get; set; }
        public Nullable<int> intIdTpoTrcro { get; set; }
        public string varAplldos1 { get; set; }
        public string varAplldos2 { get; set; }
        public string varNmbre1 { get; set; }
        public string varNmbre2 { get; set; }
        public string varFax { get; set; }
        public Nullable<int> intIdBnco { get; set; }
        public string varCuenta { get; set; }
        public Nullable<decimal> numDiasLbreCntndor { get; set; }
        public string varCiudad { get; set; }
        public string varCdSia { get; set; }
        public string varCdlaCntcto { get; set; }
        public Nullable<int> intIdTrnsprte { get; set; }
        public string varCdTrsldo { get; set; }
        public Nullable<decimal> numPrcntjeCmsion { get; set; }
        public Nullable<int> intIdTpoDcmntoIdntfccion { get; set; }
        public string varNmroTrjtaPrfcional { get; set; }
        public Nullable<int> intIdOtraClsfccionTrcro { get; set; }
        public Nullable<int> intIdRtncionIva { get; set; }
        public Nullable<int> intIdRtncionfuente { get; set; }
        public string varNmbreCmrcial { get; set; }
        public Nullable<System.DateTime> fecIncioCmoCliente { get; set; }
        public Nullable<int> intDiasVncmientoFctra { get; set; }
        public Nullable<int> intIdTpoClnte { get; set; }
        public Nullable<bool> bitActvoAlrta { get; set; }
        public Nullable<decimal> numHrasPndiente { get; set; }
        public Nullable<int> intDiasLmteCrtera { get; set; }
        public Nullable<bool> bitInclyePrcioMdloFctra { get; set; }
        public Nullable<int> intIdSctor { get; set; }
        public Nullable<decimal> numVlorHra { get; set; }
        public Nullable<int> intIdTrcroGrpoEmprsrial { get; set; }
        public string varEmailScndrio { get; set; }
        public string varDgtoVrfccion { get; set; }
        public Nullable<decimal> numPrcntjeCsion { get; set; }
        public string varAplldoNmbre { get; set; }
    
        public virtual tmCiudades tmCiudades { get; set; }
        public virtual tmPaises tmPaises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXEncabezado> tmvDEXEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvDEXEncabezado> tmvDEXEncabezado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompradores> tmCompradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmImportadorExportador> tmImportadorExportador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmImportadorExportador> tmImportadorExportador1 { get; set; }
        public virtual tmRetefuente tmRetefuente { get; set; }
        public virtual tmTransportes tmTransportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionEncabezado> tmvFacturasExportacionEncabezado1 { get; set; }
    }
}
