//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmTituloMineroProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmTituloMineroProveedor()
        {
            this.tmCompras = new HashSet<tmCompras>();
        }
    
        public int intIdTtloMnro { get; set; }
        public Nullable<int> intIdPrvdor { get; set; }
        public string varPlca { get; set; }
        public Nullable<int> intIdDueno { get; set; }
        public Nullable<int> intIdCiudad { get; set; }
        public Nullable<decimal> numPrcntje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCompras> tmCompras { get; set; }
        public virtual tmCiudades tmCiudades { get; set; }
        public virtual tmProveedores tmProveedores { get; set; }
        public virtual tmProveedores tmProveedores1 { get; set; }
    }
}
