//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmTiposDescuentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmTiposDescuentos()
        {
            this.tmvFacturasExportacionNotasCredito = new HashSet<tmvFacturasExportacionNotasCredito>();
        }
    
        public int intIdTpoDscuento { get; set; }
        public string varCdTpoDscuento { get; set; }
        public string varDscrpcionTpoDscuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionNotasCredito> tmvFacturasExportacionNotasCredito { get; set; }
    }
}
