//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmUnidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmUnidades()
        {
            this.tmInsumos = new HashSet<tmInsumos>();
            this.tmInsumos1 = new HashSet<tmInsumos>();
            this.tmInsumos2 = new HashSet<tmInsumos>();
            this.tmPosicionesArancelarias = new HashSet<tmPosicionesArancelarias>();
            this.tmCuadrosInsumoProducto = new HashSet<tmCuadrosInsumoProducto>();
            this.tmCuadrosInsumoProducto1 = new HashSet<tmCuadrosInsumoProducto>();
            this.tmvProductosFacturacion = new HashSet<tmvProductosFacturacion>();
            this.tmvFacturasExportacionDetalle = new HashSet<tmvFacturasExportacionDetalle>();
            this.tmvProductosFacturacion1 = new HashSet<tmvProductosFacturacion>();
            this.tmvProductosFacturacion2 = new HashSet<tmvProductosFacturacion>();
        }
    
        public int intIdUndad { get; set; }
        public string varCdUndad { get; set; }
        public string varDscrpcionUndadEspnol { get; set; }
        public string varAbrvtra { get; set; }
        public string varDscrpcionUndadIngles { get; set; }
        public string varUndadIntrna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmInsumos> tmInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmInsumos> tmInsumos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmInsumos> tmInsumos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmPosicionesArancelarias> tmPosicionesArancelarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCuadrosInsumoProducto> tmCuadrosInsumoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmCuadrosInsumoProducto> tmCuadrosInsumoProducto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionDetalle> tmvFacturasExportacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvProductosFacturacion> tmvProductosFacturacion2 { get; set; }
    }
}
