//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmvDEXDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmvDEXDetalle()
        {
            this.tmvFacturasExportacionDetalle = new HashSet<tmvFacturasExportacionDetalle>();
        }

        public int intIdDEXDtlle { get; set; }
        public int intIdDEX { get; set; }
        [Display(Name = "Producto")]
        public int intIdCuadroInsmoPrdcto { get; set; }
        [Display(Name = "Ítem")]
        public Nullable<int> varCdItem { get; set; }
        [Display(Name = "Cnt. U. Cmrcial")]
        public Nullable<decimal> numCntdadCnvrtir { get; set; }
        [Display(Name = "Cnt. Exportada")]
        public decimal numCntdadExprtda { get; set; }
        [Display(Name = "P. Neto")]
        public Nullable<decimal> numPsoNto { get; set; }
        [Display(Name = "Vr. FOB")]
        public decimal numVlorFOB { get; set; }
        public Nullable<decimal> numVlorVAN { get; set; }
        public Nullable<decimal> numPrcntjeVAN { get; set; }
        [Display(Name = "Vr. Reintegro")]
        public Nullable<decimal> numVlorReintrgro { get; set; }
        [Display(Name = "Bultos")]
        public Nullable<decimal> numCntdadAdcional { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Comentarios")]
        public string varCmntriosDEX { get; set; }
        public Nullable<int> intIdFctraExprtcion { get; set; }
        public Nullable<int> intRjo { get; set; }
        public Nullable<decimal> numPrcntjePrtcpcion { get; set; }
        public Nullable<bool> bitDeudaExtrna { get; set; }
        public Nullable<System.DateTime> varCdTrsldoVfpFecFctra { get; set; }
        public string varCdTrsldoVfpFctura { get; set; }
        [Display(Name = "P. Bruto")]
        public Nullable<decimal> numPsoBrto { get; set; }
        [Display(Name = "Bultos")]
        public Nullable<decimal> numBltos { get; set; }
        public string varCdAuxliar { get; set; }
        public Nullable<decimal> numValorInsmosExtrnos { get; set; }
        public Nullable<decimal> numPrcntajeInsmosExtrnos { get; set; }
        public Nullable<decimal> numFactorL { get; set; }
        
        public Nullable<bool> bitMrcar { get; set; }
    
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto { get; set; }
        public virtual tmvDEXEncabezado tmvDEXEncabezado { get; set; }
        public virtual tmvFacturasExportacionEncabezado tmvFacturasExportacionEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionDetalle> tmvFacturasExportacionDetalle { get; set; }
    }
}
