//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmvDexCorreciones
    {
        public int intIdDEXCorrcions { get; set; }
        public Nullable<int> intIdDEX { get; set; }
        public string varNmroDEX { get; set; }
        public Nullable<System.DateTime> fecAprbcionDEX { get; set; }
        public string varRtaArchvoAdjnto { get; set; }
        public string varNmroDEXCrrgdo { get; set; }
        public Nullable<System.DateTime> fecAprbcionDEXCrrgdo { get; set; }
        public Nullable<bool> bitCrrccionInfrmda { get; set; }
    
        public virtual tmvDEXEncabezado tmvDEXEncabezado { get; set; }
    }
}
