//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmvFacturasExportacionDetalle
    {
        public int intIdFctraExprtcionDtlle { get; set; }
        public int intIdFctraExprtcion { get; set; }
        [Display(Name = "Ítem")]
        public int intItem { get; set; }
        [Display(Name = "Producto")]
        public int intIdPrdctoFctrcion { get; set; }
        [Display(Name = "Cantidad")]
        public Nullable<decimal> numCntdad { get; set; }
        [Display(Name = "Vr. Unitario")]
        public Nullable<decimal> numVlorUntrio { get; set; }
        [Display(Name = "Peso Bruto")]
        public Nullable<decimal> numPsoBrto { get; set; }
        [Display(Name = "Peso Neto")]
        public Nullable<decimal> numPsoNto { get; set; }
        [Display(Name = "Subtotal")]
        public Nullable<decimal> numSbttal { get; set; }
        
        public Nullable<int> intIdCuadroInsmoPrdcto { get; set; }
        public Nullable<int> intIdCuadroInsmoPrdctoOrdnrio { get; set; }
        public Nullable<int> intIdUndadCnvrtda { get; set; }
        public Nullable<decimal> numCntdadCnvrtda { get; set; }
        public Nullable<int> intIdDexDtlle { get; set; }
        public Nullable<int> intIdTpoPlan { get; set; }
        public string varCntrto { get; set; }
        public Nullable<decimal> numGrmje { get; set; }
        public Nullable<decimal> numAncho { get; set; }
        public Nullable<decimal> numVlorUntrioPsos { get; set; }
        public Nullable<int> intIdFctraExprtcionDtlleAgrpdo { get; set; }
        public string varNmroSix { get; set; }
        public Nullable<decimal> numCntdadCntndor { get; set; }
        public string varCmntrios { get; set; }
        public Nullable<int> intIdPscionArnclria { get; set; }
        public string varLte { get; set; }
        public string varMdlo { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public Nullable<int> intIdPddoExprtcionDtlle { get; set; }
        public Nullable<decimal> numFctorCnvrsion { get; set; }
        public Nullable<int> intIdCtgria { get; set; }
        public Nullable<decimal> numDlarExprtcion { get; set; }
        public Nullable<decimal> numVlorUntrioPsosCsteo { get; set; }
        public Nullable<decimal> numPrcntjeArncelDtlle { get; set; }
        public Nullable<decimal> numPrcntjeIvaDtlle { get; set; }
        public Nullable<int> intIdCriterioOrigen { get; set; }
    
        public virtual tmvFacturasExportacionEncabezado tmvFacturasExportacionEncabezado { get; set; }
        public virtual tmvProductosFacturacion tmvProductosFacturacion { get; set; }
        public virtual tmPosicionesArancelarias tmPosicionesArancelarias { get; set; }
        public virtual tmUnidades tmUnidades { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto1 { get; set; }
        public virtual tmvDEXDetalle tmvDEXDetalle { get; set; }
    }
}
