//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmvFacturasExportacionNotasCredito
    {
        public int intIdFctraExprtcionNtaCrdto { get; set; }
        public int intIdFctraExprtcion { get; set; }
        public Nullable<int> intIdDEX { get; set; }
        public string varNmroNtaCrdto { get; set; }
        public System.DateTime fecAsientoNtaCrdto { get; set; }
        public int intIdTpoDscuento { get; set; }
        public Nullable<decimal> numVlorNtaCrdto { get; set; }
        public string varObsrvciones { get; set; }
        public Nullable<bool> bitAplca { get; set; }
    
        public virtual tmTiposDescuentos tmTiposDescuentos { get; set; }
        public virtual tmvDEXEncabezado tmvDEXEncabezado { get; set; }
        public virtual tmvFacturasExportacionEncabezado tmvFacturasExportacionEncabezado { get; set; }
    }
}
