//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmvProductosFacturacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmvProductosFacturacion()
        {
            this.tmvFacturasExportacionDetalle = new HashSet<tmvFacturasExportacionDetalle>();
        }

        public int intIdPrdctoFctrcion { get; set; }
        [Display(Name = "P. Arancelaria")]
        public int intIdPscionArnclria { get; set; }
        [Display(Name = "Descripción")]
        public string varDscrpcionEspñol { get; set; }
        [Display(Name = "Código")]
        public string varCdPrdcto { get; set; }
        public string varCdPdrePrdcto { get; set; }
        public string varDscrpcionIngles { get; set; }
        [Display(Name = "Unidad")]
        public int intIdUndad { get; set; }
        [Display(Name = "Tipo Material")]
        public Nullable<int> intIdLnea { get; set; }
        
        public Nullable<int> intIdUndadIntrna { get; set; }
        public Nullable<int> intIdUndadExtrna { get; set; }
        public Nullable<decimal> numCntdadIntrna { get; set; }
        public Nullable<decimal> numCntdadExtrna { get; set; }
        public Nullable<int> intIdCuadroInsmoPrdcto { get; set; }
        public Nullable<int> intIdCuadroInsmoPrdctoOrdnrio { get; set; }
        public Nullable<decimal> numPso { get; set; }
        public Nullable<decimal> numFctorCnvrsionDex { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public Nullable<decimal> numVlorAduana { get; set; }
        public Nullable<int> intIdRfrncia { get; set; }
        public Nullable<decimal> numPsoNto { get; set; }
        public Nullable<decimal> numPsoBrto { get; set; }
        public Nullable<decimal> numVlmen { get; set; }
        public Nullable<int> intIdNtrlza { get; set; }
        public Nullable<int> intIdTpoPrdcto { get; set; }
        public Nullable<int> intIdInsmoDTA { get; set; }
        public Nullable<decimal> numFctorInsmoDTA { get; set; }
        public Nullable<decimal> numFctorCnvrsion { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public string varUrlImgen { get; set; }
        public string varDscipcionExtndda { get; set; }
        public Nullable<decimal> numHras { get; set; }
        public Nullable<int> intIdEmpque { get; set; }
        public Nullable<bool> bitInclyeUsuario { get; set; }
        public Nullable<int> intOrden { get; set; }
        public Nullable<int> intIdImprtdorExprtdor { get; set; }
        public Nullable<decimal> numCntdadMnmaSlctud { get; set; }
        public Nullable<int> intidRfrnciaTpo { get; set; }
        public Nullable<int> intidTpoOrgenPrdcto { get; set; }
    
        public virtual tmLineas tmLineas { get; set; }
        public virtual tmPosicionesArancelarias tmPosicionesArancelarias { get; set; }
        public virtual tmUnidades tmUnidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmvFacturasExportacionDetalle> tmvFacturasExportacionDetalle { get; set; }
        public virtual tmImportadorExportador tmImportadorExportador { get; set; }
        public virtual tmInsumos tmInsumos { get; set; }
        public virtual tmUnidades tmUnidades1 { get; set; }
        public virtual tmUnidades tmUnidades2 { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto { get; set; }
        public virtual tmCuadrosInsumoProducto tmCuadrosInsumoProducto1 { get; set; }
    }
}
