//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBorradoresDexCreacion
    {
        public int intIdDEX { get; set; }
        public string varCdAuxliar { get; set; }
        public Nullable<System.DateTime> fecAuxliar { get; set; }
        public int intIdCmprdor { get; set; }
        public string varNmbre { get; set; }
        public string varNumLte { get; set; }
        public long intID { get; set; }
    }
}
