//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCpCI
    {
        public int intIdCP { get; set; }
        public string varCdCP { get; set; }
        public Nullable<System.DateTime> fecCP { get; set; }
        public Nullable<int> intIdPlanCI { get; set; }
        public Nullable<bool> bitAnldo { get; set; }
        public Nullable<System.DateTime> fecBmstre { get; set; }
        public Nullable<int> intIdPrvdor { get; set; }
        public Nullable<int> intIdCPMdfccion { get; set; }
        public Nullable<System.DateTime> fecMdfccion { get; set; }
        public string varMtvoMdfccion { get; set; }
        public Nullable<System.DateTime> fecRdccion { get; set; }
        public string varNmroCP { get; set; }
        public Nullable<System.DateTime> fecAprbcionCP { get; set; }
        public string varRtaArchvoAdjnto { get; set; }
        public string varCdPlanCI { get; set; }
        public string varDscrpcionPlanCI { get; set; }
        public string varNmbre { get; set; }
        public string varCPMdfccion { get; set; }
        public string varNumLte { get; set; }
        public Nullable<int> intCnsctvoCrgue { get; set; }
        public string varNmroCPManual { get; set; }
        public Nullable<System.DateTime> fecCPManual { get; set; }
        public Nullable<decimal> numBrtos { get; set; }
        public Nullable<decimal> numFnos { get; set; }
        public string varPrycto { get; set; }
        public string varLlve { get; set; }
    }
}
