//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDexDetalleComex
    {
        public int intIdDEXDtlle { get; set; }
        public int intIdDEX { get; set; }
        public int intIdCuadroInsmoPrdcto { get; set; }
        public Nullable<int> varCdItem { get; set; }
        public string varDscrpcionPrdcto { get; set; }
        public Nullable<decimal> numCntdadCnvrtir { get; set; }
        public decimal numCntdadExprtda { get; set; }
        public Nullable<decimal> numPsoNto { get; set; }
        public decimal numVlorFOB { get; set; }
        public Nullable<decimal> numVlorVAN { get; set; }
        public Nullable<decimal> numPrcntjeVAN { get; set; }
        public Nullable<decimal> numVlorReintrgro { get; set; }
        public Nullable<decimal> numCntdadAdcional { get; set; }
        public string varCmntriosDEX { get; set; }
        public Nullable<decimal> numPrcntjePrtcpcion { get; set; }
        public Nullable<decimal> numPsoBrto { get; set; }
        public Nullable<decimal> numBltos { get; set; }
    }
}
