//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDEX
    {
        public int intIdDEX { get; set; }
        public string varCdAuxliar { get; set; }
        public Nullable<System.DateTime> fecAuxliar { get; set; }
        public string varNmroDEX { get; set; }
        public Nullable<System.DateTime> fecAprbcionDEX { get; set; }
        public Nullable<System.DateTime> fecEmbrque { get; set; }
        public Nullable<System.DateTime> fecDeudaExtrna { get; set; }
        public int intIdImprtdorExprtdor { get; set; }
        public string varExprtdor { get; set; }
        public int intIdCmprdor { get; set; }
        public string varCmprdor { get; set; }
        public Nullable<int> intIdAduana { get; set; }
        public string varDscrpcionAduana { get; set; }
        public string varCmntrio { get; set; }
        public Nullable<decimal> numFltes { get; set; }
        public Nullable<decimal> numSgro { get; set; }
        public Nullable<decimal> numOtrosGstos { get; set; }
        public string varRtaArchvoAdjnto { get; set; }
        public Nullable<int> intIdDclrnte { get; set; }
        public string varDclrnte { get; set; }
        public Nullable<int> intIdLgarEmbrque { get; set; }
        public string varDtnoFinal { get; set; }
        public Nullable<decimal> numVlorFOB { get; set; }
        public Nullable<decimal> numExprtcionesUSD { get; set; }
        public Nullable<decimal> numVlorReintgrarUSD { get; set; }
        public Nullable<decimal> numVlorAgrgdoNcional { get; set; }
        public Nullable<decimal> numTtalSries { get; set; }
        public Nullable<decimal> numBltos { get; set; }
        public Nullable<decimal> numTtalPsoBrto { get; set; }
        public Nullable<decimal> numTtalPsoNto { get; set; }
        public string numNumroAcptcion { get; set; }
        public Nullable<System.DateTime> fecAcptcion { get; set; }
        public string varSlctudAtrzcionEmbrque { get; set; }
        public Nullable<System.DateTime> fecAtrzcionEmbrque { get; set; }
        public string varMnfiestoCrga { get; set; }
        public Nullable<System.DateTime> fecMnfiestoCrga { get; set; }
        public Nullable<int> intIdTrnsprte { get; set; }
        public string varDscrpcionTrnsprte { get; set; }
        public Nullable<int> intIdTpoPriodo { get; set; }
        public Nullable<decimal> numCntdadEmblje { get; set; }
        public Nullable<bool> bitEnviado { get; set; }
        public Nullable<int> intIdMesCntble { get; set; }
        public string varAnoCntble { get; set; }
        public Nullable<int> intIdPlanCI { get; set; }
        public string varDscrpcionPlanCI { get; set; }
        public string varNmroFrmlrioAntrior { get; set; }
        public Nullable<int> intIdDcmntoTrnsprte { get; set; }
        public string varNmroDcmntoTrnsprte { get; set; }
        public Nullable<System.DateTime> fecDcmntoTrnsprte { get; set; }
        public Nullable<int> intIdTrnsprtdor { get; set; }
        public Nullable<int> intIdFrmaPgo { get; set; }
        public Nullable<int> intIdTpoDex { get; set; }
        public int intIdPlan { get; set; }
    }
}
