//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDocumentosAdjuntosDexCIComex
    {
        public long intId { get; set; }
        public int intIdDEX { get; set; }
        public string varNumDoc { get; set; }
        public string varRtaArchvoAdjnto { get; set; }
        public string varTipoDocumento { get; set; }
        public Nullable<int> intIdCP { get; set; }
        public string varExiste { get; set; }
        public string varNbreRgmen { get; set; }
        public Nullable<int> intAno { get; set; }
    }
}
