//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFacturasExportacion
    {
        public int intIdFctraExprtcion { get; set; }
        public string varNmroAuxliar { get; set; }
        public string varNmroFctra { get; set; }
        public Nullable<System.DateTime> fecAuxliar { get; set; }
        public Nullable<System.DateTime> fecFctra { get; set; }
        public Nullable<System.DateTime> fecVncmientoFctra { get; set; }
        public int intIdCmprdor { get; set; }
        public string varCmprdor { get; set; }
        public int intIdImprtdorExprtdor { get; set; }
        public string varExprtdor { get; set; }
        public Nullable<decimal> numTsaCmbio { get; set; }
        public Nullable<decimal> numSbttal { get; set; }
        public Nullable<int> intIdIncterms { get; set; }
        public string varCdIncterms { get; set; }
        public Nullable<int> intIdMnda { get; set; }
        public Nullable<decimal> numVlorFOB { get; set; }
        public Nullable<decimal> numFltes { get; set; }
        public Nullable<decimal> numGstos { get; set; }
        public Nullable<decimal> numSgroUS { get; set; }
        public string varNmroExprtcion { get; set; }
        public Nullable<decimal> numPsoBrto { get; set; }
        public Nullable<decimal> numPsoNto { get; set; }
        public bool bitCrtra { get; set; }
        public bool bitAnlda { get; set; }
        public string varDcmntoTrnsprte { get; set; }
        public string varCdMnda { get; set; }
        public string varCdCmprdor { get; set; }
        public bool bitVntaNcional { get; set; }
        public Nullable<System.DateTime> fecExprtcion { get; set; }
    }
}
