//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFormatoOrdenesCompraCI
    {
        public string varNitImprtdorExprtdor { get; set; }
        public string varDrccion { get; set; }
        public string varTlfno { get; set; }
        public string varFax { get; set; }
        public Nullable<int> intIdCiudad { get; set; }
        public string varDscrpcionCiudad { get; set; }
        public Nullable<System.DateTime> fecCmpra { get; set; }
        public string varNmroFctra { get; set; }
        public string varNitPrvdor { get; set; }
        public string varNmbre { get; set; }
        public string varDirProveedor { get; set; }
        public string varTelProveedor { get; set; }
        public string varCiudadProveedor { get; set; }
        public string varDscrpcionDprtmnto { get; set; }
        public string varDscrpcionInsmo { get; set; }
        public Nullable<decimal> numCntdadFctra { get; set; }
        public string varCiudadMaterial { get; set; }
        public string varDepartamentoMaterial { get; set; }
        public Nullable<decimal> numLey { get; set; }
        public Nullable<decimal> numFnos { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public Nullable<decimal> numSbttal { get; set; }
        public Nullable<decimal> numVlorRglias { get; set; }
        public Nullable<decimal> numPrcntjeIva { get; set; }
        public Nullable<decimal> numVlorIva { get; set; }
        public Nullable<decimal> numVlorRtncionFuente { get; set; }
        public Nullable<decimal> numValorPagar { get; set; }
        public Nullable<decimal> TotalFactura { get; set; }
        public decimal numRegaliasPlataOro { get; set; }
        public Nullable<decimal> numVlorPorGrmo { get; set; }
        public int intIdCmpra { get; set; }
        public Nullable<int> intIdUsuario { get; set; }
        public decimal numFnosPlataOro { get; set; }
        public decimal numLeyPlataOro { get; set; }
        public string varNmbreEmprsa { get; set; }
        public string varFctra { get; set; }
        public decimal numRegaliasPlatinoOro { get; set; }
        public decimal numFnosPlatinoOro { get; set; }
        public decimal numLeyPlatinoOro { get; set; }
        public string varFairminedId { get; set; }
        public string varFairminedIdAnexpo { get; set; }
    }
}
