//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFormatoDocEquivalenteCINuevo
    {
        public int intIdCmpra { get; set; }
        public string varRzonSocial { get; set; }
        public string varDrccion { get; set; }
        public string varTlfno { get; set; }
        public string varEmail { get; set; }
        public string varTxtoDcrto { get; set; }
        public string varCdAuxliar { get; set; }
        public string varNmroFctra { get; set; }
        public Nullable<System.DateTime> fecCmpra { get; set; }
        public string varNmbre { get; set; }
        public string varDrccionPrvdor { get; set; }
        public string varDscrpcionCiudad { get; set; }
        public string varDscrpcionDprtmnto { get; set; }
        public string varNitPrvdor { get; set; }
        public string varTlfnoPrvdor { get; set; }
        public Nullable<decimal> numCntdadFctra { get; set; }
        public string varDscrpcionInsmo { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public Nullable<decimal> numSbttal { get; set; }
        public Nullable<decimal> numVlorRglias { get; set; }
        public Nullable<decimal> numVlorRtncionFuente { get; set; }
        public Nullable<decimal> numVlorRteIva { get; set; }
        public Nullable<decimal> numValorTtal { get; set; }
        public string varNtas { get; set; }
        public string varNumLte { get; set; }
        public string varNitImprtdorExprtdor { get; set; }
        public string varTxtoRslcion { get; set; }
        public string varPrfjo { get; set; }
        public string varNumDocEquvlnte { get; set; }
    }
}
