//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInformeAnualCi
    {
        public long intNum { get; set; }
        public string varCdCP { get; set; }
        public Nullable<System.DateTime> fecBmstre { get; set; }
        public Nullable<System.DateTime> fecCP { get; set; }
        public Nullable<long> intNumItem { get; set; }
        public string varNmroFctra { get; set; }
        public Nullable<System.DateTime> fecCmpra { get; set; }
        public decimal numVlorCp { get; set; }
        public Nullable<decimal> numVlorTtalAnual { get; set; }
        public string varPrdctoSinTrnsfrmar { get; set; }
        public string varMtriaPrima { get; set; }
        public string varSrvcioIntrmdioPrdccion { get; set; }
        public Nullable<System.DateTime> fecEnvioCP { get; set; }
        public string varNmroDEX { get; set; }
        public Nullable<System.DateTime> fecAprbcionDEX { get; set; }
        public string varCdAduana { get; set; }
        public Nullable<System.DateTime> fecEmbrque { get; set; }
        public decimal numVlrTtalFobUSD { get; set; }
        public decimal numVlrFobUSD { get; set; }
        public string Proveedor { get; set; }
        public string DocProv { get; set; }
        public string varCdAuxliar { get; set; }
    }
}
