//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInformeUIAFCompVent
    {
        public int intIdFctra { get; set; }
        public string FecTransaccion { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string TipoOperacion { get; set; }
        public string TipoDocumento { get; set; }
        public string Identificacion { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string RazonSocial { get; set; }
        public string varCd { get; set; }
        public Nullable<decimal> numCntdadFctra { get; set; }
        public int FormaPago { get; set; }
        public string Detalles { get; set; }
        public string Lote { get; set; }
        public string varCdAuxliar { get; set; }
        public Nullable<int> Cargue { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
