//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInformeUIAFImpExp
    {
        public Nullable<long> intConsec { get; set; }
        public string fecha { get; set; }
        public Nullable<decimal> numVlrfob { get; set; }
        public Nullable<decimal> numVlrfob2 { get; set; }
        public string varTipomon { get; set; }
        public string varTipoDoc { get; set; }
        public string varNit { get; set; }
        public string varPrimerApellido { get; set; }
        public string varSegundoApellido { get; set; }
        public string varPrimerNombre { get; set; }
        public string varSegundoNombre { get; set; }
        public string varRazonSocial { get; set; }
        public string varCoddane { get; set; }
        public int intTipotra { get; set; }
        public string varNitdetalle { get; set; }
        public string varNit2 { get; set; }
        public string varPrimerApellido1 { get; set; }
        public string varSegundoApellido1 { get; set; }
        public string varPrimerNombre1 { get; set; }
        public string varSegundoNombre1 { get; set; }
        public string varRazonSocial1 { get; set; }
        public string varPais { get; set; }
        public string varCiudad { get; set; }
        public string varPartidaa { get; set; }
        public string varDex { get; set; }
        public int intFormap { get; set; }
        public string varDetalle { get; set; }
        public Nullable<System.DateTime> fecFctra { get; set; }
        public string varNumLte { get; set; }
    }
}
