//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInventarioCp
    {
        public int intIdCP { get; set; }
        public string varCdCP { get; set; }
        public Nullable<System.DateTime> fecCP { get; set; }
        public string varProveedor { get; set; }
        public string varCI { get; set; }
        public Nullable<decimal> numCntdadCnsmda { get; set; }
        public Nullable<int> intIdCPDtlle { get; set; }
        public string varCdPlanCI { get; set; }
        public string varDscrpcionPlanCI { get; set; }
        public Nullable<int> intIdPlanCI { get; set; }
        public Nullable<decimal> numCntdadCp { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public string varDscrpcionInsmo { get; set; }
        public Nullable<decimal> numCntdadPndienteCP { get; set; }
        public Nullable<bool> bitEdcionMnual { get; set; }
        public Nullable<decimal> numVlorCpPorCI { get; set; }
        public Nullable<decimal> numCntCnsmdaDEX { get; set; }
        public Nullable<decimal> numVlorCnsmdoCpPorCI { get; set; }
        public Nullable<decimal> numVlorPndienteCpPorCI { get; set; }
        public string varRtaArchvoAdjnto { get; set; }
        public string varNmroCP { get; set; }
        public Nullable<System.DateTime> fecAprbcionCP { get; set; }
        public string varUndadCP { get; set; }
        public string varSemaforo { get; set; }
    }
}
