//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrdenesCompraCI
    {
        public int intIdCmpra { get; set; }
        public string varCdAuxliar { get; set; }
        public string varNmroFctra { get; set; }
        public Nullable<System.DateTime> fecCmpra { get; set; }
        public int intIdPrvdor { get; set; }
        public Nullable<int> intIdRtncionfuente { get; set; }
        public Nullable<decimal> numVlorRtncionFuente { get; set; }
        public Nullable<decimal> numVlorIva { get; set; }
        public Nullable<bool> bitAnldo { get; set; }
        public Nullable<int> intIdCP { get; set; }
        public Nullable<decimal> numPrcntjeRtncionFte { get; set; }
        public Nullable<decimal> numVlorTtal { get; set; }
        public Nullable<int> intIdAdquirdaTpoCmpra { get; set; }
        public Nullable<int> intIdRslcion { get; set; }
        public string varDscrpcionTpoCmpra { get; set; }
        public Nullable<int> intIdCiudadRglias { get; set; }
        public Nullable<decimal> numVlorRglias { get; set; }
        public Nullable<int> intCnsctvoCrgue { get; set; }
        public Nullable<int> intIdRglia { get; set; }
        public Nullable<int> intIdTtloMnro { get; set; }
        public Nullable<bool> bitAcgdosLey1429 { get; set; }
        public string varNumLte { get; set; }
        public Nullable<System.DateTime> fecPgoRglia { get; set; }
        public string varNumRglia { get; set; }
        public string varNmbre { get; set; }
        public string varCdCP { get; set; }
        public Nullable<System.DateTime> fecCp { get; set; }
        public string varNmroCP { get; set; }
        public Nullable<System.DateTime> fecAprbcionCP { get; set; }
        public string varDscrpcionAdquirdaTpoCmpra { get; set; }
        public string NmroRslcion { get; set; }
        public string varDscrpcionCiudadRglias { get; set; }
        public string varDscrpcionDprtmntoRglias { get; set; }
        public string varRegalias { get; set; }
        public string varPlcaTtloMnro { get; set; }
        public string varNitPrvdor { get; set; }
        public string varNmroRslcion { get; set; }
        public Nullable<decimal> numBrtos { get; set; }
        public Nullable<decimal> numFnos { get; set; }
        public string varPrycto { get; set; }
        public string varLlve { get; set; }
    }
}
