//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrdenesCompraDetalleCI
    {
        public int intIdCmpraDtlle { get; set; }
        public Nullable<int> intIdCmpra { get; set; }
        public Nullable<int> intCdItem { get; set; }
        public int intIdInsmo { get; set; }
        public Nullable<decimal> numCntdadFctra { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public Nullable<decimal> numCntdadCP { get; set; }
        public Nullable<decimal> numSbttal { get; set; }
        public Nullable<decimal> numPrcntjeIva { get; set; }
        public Nullable<int> intIdAdqurdasTtlo { get; set; }
        public string varCmntrios { get; set; }
        public Nullable<int> intIdCPDtlle { get; set; }
        public Nullable<decimal> numFnos { get; set; }
        public Nullable<decimal> numLey { get; set; }
        public Nullable<decimal> numRglias { get; set; }
        public Nullable<int> intIdRglia { get; set; }
        public Nullable<decimal> numVlorUntrioUS { get; set; }
        public Nullable<decimal> numPorcMnria { get; set; }
        public string varCdInsmo { get; set; }
        public string varDscrpcionInsmo { get; set; }
        public string varDscrpcionAdquirda { get; set; }
        public string varRegalias { get; set; }
        public decimal numCantAcumNotasCrdto { get; set; }
        public decimal numVlorAcumNotasCrdto { get; set; }
    }
}
