//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPdfCpManualDetalle
    {
        public string nfact { get; set; }
        public Nullable<System.DateTime> ffac { get; set; }
        public string resfac { get; set; }
        public Nullable<System.DateTime> fres { get; set; }
        public Nullable<int> tipo { get; set; }
        public string desctipo { get; set; }
        public string subp { get; set; }
        public string desc { get; set; }
        public Nullable<decimal> cunfi { get; set; }
        public string unfi { get; set; }
        public string descunfi { get; set; }
        public Nullable<decimal> cunco { get; set; }
        public string unco { get; set; }
        public string descunco { get; set; }
        public Nullable<decimal> vuni { get; set; }
        public Nullable<decimal> vtotal { get; set; }
        public decimal tiva { get; set; }
        public decimal vexen { get; set; }
        public string codins { get; set; }
        public int cp_Id { get; set; }
        public Nullable<System.DateTime> fecCP { get; set; }
    }
}
