//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProveedores
    {
        public int intIdPrvdor { get; set; }
        public string varCdPrvdor { get; set; }
        public string varNmbre { get; set; }
        public string varDrccion { get; set; }
        public string varTlfno { get; set; }
        public int intIdPais { get; set; }
        public string varDscrpcionPais { get; set; }
        public Nullable<bool> bitPrveedorNcional { get; set; }
        public string varAplldos { get; set; }
        public Nullable<int> intIdCiudad { get; set; }
        public string varCdCiudad { get; set; }
        public string varDscrpcionCiudad { get; set; }
        public string varAbrvtra { get; set; }
        public Nullable<int> intIdDprtmnto { get; set; }
        public string varCdDprtmnto { get; set; }
        public string varDscrpcionDprtmnto { get; set; }
        public string varCdPais { get; set; }
        public string varEmail { get; set; }
        public string varNmbre1 { get; set; }
        public string varAplldos1 { get; set; }
        public string varNitPrvdor { get; set; }
        public string varNmbre2 { get; set; }
        public string varNbreRgmen { get; set; }
        public Nullable<int> intIdRgmen { get; set; }
        public bool bitBlqueado { get; set; }
        public string varAbrviatraArchvos { get; set; }
        public Nullable<bool> bitAcgdosLey1429 { get; set; }
        public string varFairminedId { get; set; }
        public string varCiudad { get; set; }
        public string varFax { get; set; }
        public Nullable<int> intIdBnco { get; set; }
        public string varDscrpcionBnco { get; set; }
        public Nullable<int> intIdMnda { get; set; }
        public string varDscrpcionMndaEspnol { get; set; }
        public Nullable<int> intIdIncterms { get; set; }
        public string varDsIncterms { get; set; }
        public string varCuenta { get; set; }
        public Nullable<int> intIdFrmaPgo { get; set; }
        public string varDscrpcionFrmaPgo { get; set; }
        public Nullable<decimal> numdiaspgo { get; set; }
        public Nullable<int> intIdCndcionPrvdor { get; set; }
        public string varNmbreCndcionPrvdor { get; set; }
        public string varOtraCndcion { get; set; }
        public Nullable<decimal> numrtncionfnte { get; set; }
        public Nullable<int> intIdTpoPrvdor { get; set; }
        public string varNmbreTpoPrvdor { get; set; }
        public string varCmpniaInter { get; set; }
        public Nullable<int> intIdClsfccionPrvdor { get; set; }
        public string varNmbreClsfccionPrvdor { get; set; }
        public Nullable<decimal> numprcntjeantcpo { get; set; }
        public Nullable<int> intIdCmpnia { get; set; }
        public string varNmbreCmpnia { get; set; }
        public string varCdPdrePrvdor { get; set; }
        public Nullable<int> intIdLgarEmbrque { get; set; }
        public string varNmbreLgarEmbrque { get; set; }
        public Nullable<bool> bitMrcar { get; set; }
        public string varClveWeb { get; set; }
        public string varAbrvtraPrvdor { get; set; }
        public string varCdCndcionPrvdor { get; set; }
        public string varCdPstal { get; set; }
        public string varCdgoSwift { get; set; }
        public string varCdgoBIC { get; set; }
        public string varCdgoIBAN { get; set; }
        public string varCdgoABA { get; set; }
        public string varCdgoCAB { get; set; }
        public string varCdClsifccionPrvdor { get; set; }
        public Nullable<decimal> numPrcntjeOro { get; set; }
        public Nullable<decimal> numPrcntjePlta { get; set; }
        public Nullable<decimal> numPrcntjPltno { get; set; }
    }
}
