//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReporteOrdenesCompraCI
    {
        public int intIdCmpra { get; set; }
        public Nullable<int> intCnsctvoCrgue { get; set; }
        public string varNumLte { get; set; }
        public string varCdAuxliarCmpra { get; set; }
        public string varNmroFctra { get; set; }
        public Nullable<System.DateTime> fecCmpra { get; set; }
        public string varNitPrvdor { get; set; }
        public string varNmbrePrvdor { get; set; }
        public string varDscrpcionInsmo { get; set; }
        public Nullable<decimal> numCntdadFctra { get; set; }
        public Nullable<decimal> numFnos { get; set; }
        public decimal numFnosAG { get; set; }
        public Nullable<decimal> numLey { get; set; }
        public decimal numLeyAG { get; set; }
        public Nullable<decimal> numVlorUntrio { get; set; }
        public Nullable<decimal> numRglias { get; set; }
        public decimal numRgliasAG { get; set; }
        public Nullable<decimal> numVlorRtncionFuente { get; set; }
        public Nullable<decimal> numValorPagar { get; set; }
        public Nullable<decimal> numValorAntesRetencion { get; set; }
        public Nullable<decimal> numSbttal { get; set; }
        public Nullable<bool> bitAcgdosLey1429 { get; set; }
        public string varDscrpcionCiudad { get; set; }
        public string varDrccion { get; set; }
        public Nullable<int> intIdRgmen { get; set; }
        public string varNbreRgmen { get; set; }
        public Nullable<decimal> numVlorPorGrmo { get; set; }
        public Nullable<int> intAnoCmpra { get; set; }
        public Nullable<int> intMesCmpra { get; set; }
        public Nullable<int> intDiaCmpra { get; set; }
        public string varCiudadRglias { get; set; }
        public string varDepartamentoRglias { get; set; }
        public string varCdCP { get; set; }
        public Nullable<System.DateTime> fecCp { get; set; }
        public string varNmroCP { get; set; }
        public Nullable<System.DateTime> fecAprbcionCP { get; set; }
        public string varCdAuxliarDEX { get; set; }
        public Nullable<System.DateTime> fecAuxliar { get; set; }
        public string varNmroDEX { get; set; }
        public Nullable<System.DateTime> fecAprbcionDEX { get; set; }
        public Nullable<decimal> numVlorFOB { get; set; }
        public string varNmbreCmprdor { get; set; }
        public string varDscrpcionPais { get; set; }
        public string varNmroExprtcion { get; set; }
        public decimal numFnosPT { get; set; }
        public decimal numLeyPT { get; set; }
        public decimal numRgliasPT { get; set; }
        public string varPrycto { get; set; }
        public string varLlve { get; set; }
    }
}
