//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vResolucionFactActualProveedor
    {
        public int intIdRslcion { get; set; }
        public Nullable<int> intIdPrvdor { get; set; }
        public string NmroRslcion { get; set; }
        public string NmroRslcionDsde { get; set; }
        public string NmroRslcionHsta { get; set; }
        public Nullable<System.DateTime> FecVncmientoRslcion { get; set; }
        public string varPrfjo { get; set; }
    }
}
