//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComEx.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vXmlCIDiarioEncabezado
    {
        public string cpto { get; set; }
        public int tdoc { get; set; }
        public string ndoc { get; set; }
        public string apl1 { get; set; }
        public string apl2 { get; set; }
        public string nom1 { get; set; }
        public string nom2 { get; set; }
        public string razsoc { get; set; }
        public string nforant { get; set; }
        public Nullable<System.DateTime> fecfant { get; set; }
        public Nullable<int> cantfac { get; set; }
        public Nullable<decimal> vtcons { get; set; }
        public decimal vtexen { get; set; }
        public Nullable<System.DateTime> flimexp { get; set; }
        public Nullable<int> nitems { get; set; }
        public int mas_id { get; set; }
        public int cp_Id { get; set; }
        public Nullable<System.DateTime> fecCP { get; set; }
    }
}
